version: "3"

services:
  cordelia:
    build: .
    # image: crdnl/cordelia2
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cordelia
      POSTGRES_PASSWORD: example
      POSTGRES_USER: personal
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080