version: '3.1'

services:

  cordelia:
    image: node:lts
    volumes:
      - .:/app
    command: node /app/app.js

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cordelia
      POSTGRES_PASSWORD: example
      POSTGRES_USER: personal
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080